services:
  demo_racecondition:
    image: ${DOCKER_REGISTRY-}demoracecondition
    build:
      context: .
      dockerfile: demo_RaceCondition/Dockerfile
    ports:
      - "7212:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,3306;Database=demo_bypass;User ID=root;Password=123;
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: demo_bypass
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql_dump:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
