version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: 123

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydatabase
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql_dump:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
