version: '3.8'

services:
  ssrf-demo:
    image: ssrf-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

volumes:
  mongo-data:
    driver: local

networks:
  internal:
    driver: bridge